<?php declare(strict_types=1);

namespace Circli\WebCore;

use Circli\WebCore\Exception\AccessDenied;
use StyleWish\Modules\ArtemisBase\Web\Error\Actions\NotFoundAction;

class ActionDispatcher extends \Polus\Adr\ActionDispatcher
{
    protected function handleInputException(\Throwable $e)
    {
        if ($e instanceof NotFoundAction) {
            return $this->getResponseFactory()->createResponse(404);
        }
        if ($e instanceof AccessDenied) {
            return $this->getResponseFactory()->createResponse(403);
        }
        return parent::handleInputException($e); // TODO: Change the autogenerated stub
    }
}